version: '3'
services:

  angular-server:
    container_name: angular-cli-dev-server
    image: angular-cli-dev-server
    build:
      context: .
      dockerfile: ./docker/server/dockerfile
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    ports:
      - "3000:4200"
    networks:
      - node-network

  angular-test:
    container_name: angular-cli-dev-tests
    image: angular-cli-dev-tests
    build:
      context: .
      dockerfile: ./docker/tests/dockerfile
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    ports:
      - "3030:9876"
    networks:
      - node-network

networks:
  node-network:
    driver: bridge