version: '3'
services:
  angular:
    container_name: angular_app
    image: my-dream-app
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    ports:
      - "3000:4200"
    networks:
      - node-network

networks:
  node-network:
    driver: bridge